Repository Shopify/hydrogen, pull requests merged in 2024-06, with the labels that each got.

#2197 Update cli-kit and cli to bundled versions
  examples/express/package.json
  examples/multipass/package.json
  examples/partytown/package.json
  examples/subscriptions/package.json
  package-lock.json
  package.json
  packages/cli/package.json
  templates/hello-world/package.json
  templates/skeleton/package.json
Labels: 2024.7

#2185 Update TSUP version
  package-lock.json
  package.json
  packages/cli/src/commands/hydrogen/env/list.ts
  packages/cli/src/commands/hydrogen/env/pull.ts
  packages/cli/src/commands/hydrogen/env/push.ts
  packages/cli/src/lib/onboarding/common.ts
Labels: 2024.7

#2148 Remove `@shopify/cli-hydrogen` dependency from starter dependencies
  packages/cli/src/lib/onboarding/remote.test.ts
  packages/cli/src/lib/onboarding/remote.ts
  packages/cli/src/lib/template-diff.ts
  packages/cli/tsup.config.ts
Labels: 2024.7

#2182 AuthBypassTokenDuration CLI Additions
  .changeset/young-gifts-learn.md
  packages/cli/oclif.manifest.json
  packages/cli/src/commands/hydrogen/deploy.test.ts
  packages/cli/src/commands/hydrogen/deploy.ts
Labels: Feature

#2113 Don't filter product options with only one value in the VariantSelector
  .changeset/cold-foxes-draw.md
  examples/b2b/app/routes/products.$handle.tsx
  packages/hydrogen/src/product/VariantSelector.test.ts
  packages/hydrogen/src/product/VariantSelector.ts
  templates/skeleton/app/routes/products.$handle.tsx
Labels: 2024.7

#2219 Fix typo and expand getSeoMeta doc example
  packages/hydrogen/src/seo/getSeoMeta.example.tsx
Labels: cla-needed
